### ISSUE TITLE
Documentatuon of its *range* capabilities is needed... 

### ISSUE THREAD

**Issue by davidbuzz** [IgrikXD/WSPR-beacon#1]
Eg, it was recieved by a wspr reciever X km away when conneted to X antenna and transmitting on frequency X

**Comment by IgrikXD** [comment]
> Eg, it was recieved by a wspr reciever X km away when conneted to X antenna and transmitting on frequency X

Such documentation is completely uninformative. **With the same antenna and on the same frequency, two different people can get completely different results. Why is that?** This may be due to:

1. Different geographic locations of the two different transmitting beacons and their varying distances from the WSPR receivers;
2. Differences in transmission times (_propagation in some bands depends on the time of day_);
3. Differences in antenna setup - the same antenna can be tuned differently and installed in completely different conditions (_one is in an open field outside the city, the other in an urban area_);
4. Differences in output amplifier settings;
5. Differences in the filters used;

**Adding such information is only relevant as a report from a specific user, with a description of the equipment used and the transmission conditions.** I could conduct such tests, but their results would not guarantee that another user would be able to reproduce the same results.

However, I like your idea, and I will consider the possibility of adding a separate table with reports on the device's performance from real users in the future. Changes to such a table could be made via a Pull Request. **If you have ideas for an alternative implementation, I would be happy to consider them!**

**Comment by davidbuzz** [comment]
Personally, I'm basically just trying to understand wether, for a given setup, I should expect 10meters range, 100meters range, 1kmrange, 10km range , 100km range. :-)

**Comment by IgrikXD** [comment]
> Personally, I'm basically just trying to understand wether, for a given setup, I should expect 10meters range, 100meters range, 1kmrange, 10km range , 100km range. :-)

I plan to conduct field tests outside the city soon on the 7 and 14 MHz bands. Once I have the results, I will definitely share them! I think I will add an additional table of the obtained results to the repository.

**Comment by IgrikXD** [comment]
**Device test report added:** https://github.com/IgrikXD/WSPR-beacon/blob/master/Device-test-report.md
